### ISSUE TITLE
Problem with newick file

### ISSUE THREAD

**Issue by rungi1** [uym2/wLogDate#4]
Hello,

I was trying to run wLogDate on my newick tree and I am always get an error.

I have installed version 1.0.2. on windows and have tried some of the use cases (e.g. viruas_all_samplingTime) and it works without problems.
When I try running wLogDate I get following error:
```
launch_wLogDate -i tree.nwk -o test.tre
Traceback (most recent call last):
  File "launch_wLogDate.py", line 107, in <module>
  File "launch_wLogDate.py", line 101, in main
  File "logdate\logD_lib.py", line 321, in logDate_with_random_init
  File "logdate\fixed_init_lib.py", line 287, in random_date_init
  File "logdate\fixed_init_lib.py", line 240, in get_random_initial
  File "logdate\fixed_init_lib.py", line 119, in calibrate_set
  File "logdate\fixed_init_lib.py", line 211, in date_from_root_and_leaves
AssertionError
[7276] Failed to execute script launch_wLogDate
```
A very small part of my tree works:
```
sub2 <- (((20180731_AD309:0,20180424_AD135:0)0.53:0.01579234639,20180921_AD445:0)0.34:0.0004192878857,20180424_AD136:0)0.37:0.00330139461;
launch_wLogDate -i sub2.txt -o test.tre
INFO:logD_lib:Finished initialization with random seed 59
INFO:logD_lib:Initial state:
INFO:logD_lib:mu = 4178.792346077013
INFO:logD_lib:fx = 10.319221201823028
INFO:logD_lib:Maximum constraint violation: 0.0
`xtol` termination condition is satisfied.
Number of iterations: 130, function evaluations: 130, CG iterations: 139, optimality: 2.12e-03, constraint violation: 7.62e-09, execution time: 0.16 s.
INFO:logD_lib:Found local optimal for Initial point 1
INFO:logD_lib:Found a better log-scored configuration
INFO:logD_lib:New mutation rate: 4178.797566026466
INFO:logD_lib:New log score: 9.681770497972913
INFO:main:Clock rate: 4178.797566026466
INFO:main:Log score: 9.681770497972913
```
Increasing the tree length by a single individual leads failure again, but after increasing branch lengths of 0 to 5e-04 it works agin.
```
sub3 <-((((20180731_AD309:0,20180424_AD135:0)0.53:0.01579234639,20180921_AD445:0)0.34:0.0004192878857,20180424_AD136:0)0.37:0.00330139461,20181122_AD624:0)0.38:0.003694297016;

INFO:main:Launching wLogDate version 1.0.2
INFO:main:wLogDate was called as follow: launch_wLogDate -i sub3.txt -o test.tre
WARNING:fixed_init_lib:few calibration points were given. Set min_nleaf to 1 to maximize the number of possible initials
Traceback (most recent call last):
  File "launch_wLogDate.py", line 107, in <module>
  File "launch_wLogDate.py", line 101, in main
  File "logdate\logD_lib.py", line 321, in logDate_with_random_init
  File "logdate\fixed_init_lib.py", line 287, in random_date_init
  File "logdate\fixed_init_lib.py", line 240, in get_random_initial
  File "logdate\fixed_init_lib.py", line 119, in calibrate_set
  File "logdate\fixed_init_lib.py", line 211, in date_from_root_and_leaves
AssertionError
[8064] Failed to execute script launch_wLogDate

sub3_mod <- ((((20180731_AD309:5e-04,20180424_AD135:5e-04)0.53:0.01579234639,20180921_AD445:5e-04)0.34:0.0004192878857,20180424_AD136:5e-04)0.37:0.00330139461,20181122_AD624:5e-04)0.38:0.003694297016;

INFO:main:Launching wLogDate version 1.0.2
INFO:main:wLogDate was called as follow: launch_wLogDate -i sub3_mod.txt -o test.tre
WARNING:fixed_init_lib:few calibration points were given. Set min_nleaf to 1 to maximize the number of possible initials
INFO:logD_lib:Finished initialization with random seed 462
INFO:logD_lib:Initial state:
INFO:logD_lib:mu = 0.031637396845169065
INFO:logD_lib:fx = 1.5127234220483183
INFO:logD_lib:Maximum constraint violation: 0.0
`gtol` termination condition is satisfied.
Number of iterations: 73, function evaluations: 91, CG iterations: 86, optimality: 6.98e-09, constraint violation: 8.67e-19, execution time: 0.12 s.
INFO:logD_lib:Found local optimal for Initial point 1
INFO:logD_lib:Found a better log-scored configuration
INFO:logD_lib:New mutation rate: 0.008324537876730067
INFO:logD_lib:New log score: 0.6130328618871983
INFO:main:Clock rate: 0.008324537876730067
INFO:main:Log score: 0.6130328618871983

```
However changing the branch lengths on the complete tree does not resolve the error and having a branch length of 0 shouldn't be a problem, as the program should then also have failed with sub2.
I am sorry if I overlooked something, but I didn't find the requirements for the tree on the page or in the paper. It would be great, if you could tell me what the problem ist.
I am happy to share the complete tree for further testing.

**Comment by smirarab** [comment]
Uyen, can you look into this? My guess is that it has to do with 0 branch lengths, but not in trivial ways. Also, if there is something wrong in the tree, we should perhaps make the error more interpretable.

**Comment by VR-Daniel** [comment]
I'm also having the same issue in version 1.0.4 but only when include the -p argument.
